### PR TITLE
Pull request for allow-to-make-call

### PR DESCRIPTION
**Pull request by fblackburn1**
Depends-on: https://github.com/wazo-platform/wazo-agid/pull/87

### CODE REVIEW

**Comment by fblackburn1** [comment]
recheck

**Review by sduthil — APPROVED** [review]

**Comment by sduthil** [comment]
Nice job, it worked at the first try :)
Only missing thing IMHO is some checks in `verify.sh`, but that's not blocking.

**Comment by fblackburn1** [comment]
> Only missing thing IMHO is some checks in `verify.sh`, but that's not blocking.

Oh please tell me some ideas. I try to focus on check/error that happen in real life (i.e. someone already has)
But if you have good idea to improve robustness, got for it
constraints:
* minimal external dependency (ex: no python)
* no over complicate check that is un-maintenable

**Comment by sduthil** [comment]
I don't have any ideas with those constraints. For the records, the constraints are here to make the script as portable as possible.

**Pull request merged**
